services:
  # Backend API
  - type: web
    name: events-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    autoDeploy: false
    rootDir: ./mock

  # Frontend Static Site
  - type: web
    name: events-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://events-api.onrender.com
    autoDeploy: false
